name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.1
        composer_version: 1
    - uses: php-actions/composer@v5

